version: "2.2"

services:
  mysql:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'userservice'
      MYSQL_USER: 'mysql-user'
      MYSQL_PASSWORD: 'pass123'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  spring:
    container_name: backend
    build:
      context: reference-letter-spring-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  vuejs:
    container_name: frontend
    build:
      context: reference-letters-vuejs-client
      dockerfile: Dockerfile
    volumes:
      - './reference-letters-vuejs-client:/app'
      - '/app/node_modules'
    env_file:
      - reference-letters-vuejs-client/.env
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - spring

volumes:
  my-db: